apiVersion: pipeline.knative.dev/v1alpha1
kind: Task
metadata:
  name: echo-image-digest
  namespace: default
spec:
  inputs:
    resources:
    - name: builtImage
      type: image
    # The workspace must be an output from a step that writes kanikoLog,
    # i.e. the pipeline must have providedBy for this input
    - name: workspace
      type: git
    params:
    - name: kanikoLog
      description: Where to direct Kaniko's stdout (a workaround until PipelineParams and log collection is implemented)
      default: "kanikolog.txt"
  steps:
  - name: echo
    image: gcr.io/kaniko-project/executor:debug
    command:
    - /busybox/sh
    args:
    - -c
    - |
      echo ${inputs.resources.builtImage.url}
      echo ${inputs.resources.builtImage.digest}
      echo ${inputs.params.kanikoLog}
      stat ${inputs.params.kanikoLog}
      tail -n 3 ${inputs.params.kanikoLog}
      PUSHED=$(tail -n 1 ${inputs.params.kanikoLog})
      DIGEST=$(expr "$PUSHED" : '.*digest: \(sha256:[a-f0-9]*\).*')
      [ -z "$DIGEST" ] && echo "Failed to find digest in Kaniko output" && exit 1
      echo "Digest: $DIGEST"
