apiVersion: pipeline.knative.dev/v1alpha1
kind: Task
metadata:
  name: echo-image-digest
  namespace: default
spec:
  inputs:
    resources:
    - name: builtImage
      type: image
    # The workspace is needed for kanikLog
    - name: workspace
      type: git
    params:
    - name: kanikoLog
      description: Where to direct Kaniko's stdout (a workaround until PipelineParams and log collection is implemented)
      defalt: "kanikolog.txt"
  steps:
  - name: echo
    image: gcr.io/kaniko-project/executor:debug
    command:
    - /busybox/sh
    args:
    - -c
    - |
      echo ${inputs.resources.builtImage.url}
      echo ${inputs.params.kanikoLog}
