apiVersion: pipeline.knative.dev/v1alpha1
kind: Pipeline
metadata:
  name: echo-image-digest
  namespace: default
spec:
  tasks:
  - name: build-and-push
    taskRef:
      name: nodejs-riff-function-build
    params:
    - name: directory
      value: ./example-module
    - name: functionName
      value: ""
    - name: reproducible
      value: "true"
    - name: kanikoLog
      value: nodejs-riff-module.kanikolog.txt
  - name: echo
    taskRef:
      name: echo-image-digest
    resources:
      - name: workspace
        providedBy: [build-and-push]
      - name: builtImage
        # but we're not getting a Digest https://github.com/knative/build-pipeline/blob/476262127199e67701d59418b2631467564dcdf5/pkg/apis/pipeline/v1alpha1/image_resource.go#L51
        providedBy: [build-and-push]
    params:
    - name: kanikoLog
      value: nodejs-riff-module.kanikolog.txt
