---
apiVersion: pipeline.knative.dev/v1alpha1
kind: PipelineResource
metadata:
  name: nodejs-riff-module-git
  namespace: default
spec:
  type: git
  params:
  - name: url
    value: https://github.com/triggermesh/nodejs-runtime.git
  - name: revision
    value: HEAD
  - name: directory
    value: ./example-module
---
apiVersion: pipeline.knative.dev/v1alpha1
kind: PipelineResource
metadata:
  name: nodejs-riff-module-image
  namespace: default
spec:        
  type: image
  params:
  - name: url
    value: knative.registry.svc.cluster.local/knative-training/nodejs-riff-module:latest
