apiVersion: pipeline.knative.dev/v1alpha1
kind: TaskRun
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: nodejs-riff
spec:
  taskRef:
    name: nodejs-riff-function-build
  trigger:
    triggerRef:
      type: manual
  inputs:
    resources:
    - name: workspace
      resourceRef:
        name: nodejs-riff-module-git
    params:
    - name: directory
      value: ./example-module
    - name: functionName
      value: ""
  outputs:
    resources:
    - name: builtImage
      resourceRef:
        name: nodejs-riff-module-image
    params:
    - name: reproducible
      value: "true"
