apiVersion: build.knative.dev/v1alpha1
kind: BuildTemplate
metadata:
  name: kaniko
spec:
  parameters:
  - name: IMAGE
    description: The name of the image to push
  - name: DOCKERFILE
    description: Path to the Dockerfile to build.
    default: /workspace/Dockerfile
  steps:
  - name: build-and-push
    image: gcr.io/kaniko-project/executor@sha256:2c62140e915a880b4959ef90e413070c2b8cf6e83ceacb9cbc560324564fa577
    args:
    - --dockerfile=${DOCKERFILE}
    - --destination=${IMAGE}
